/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the session.
         *
         *     Idempotent, and silent about whether the token was real. A client retrying over a
         *     flaky connection must not see an error, and an attacker must not learn from a
         *     logout whether a token they hold is valid.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_v1_auth_me_patch"];
        trace?: never;
    };
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Google Sign In */
        post: operations["google_sign_in_api_v1_auth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_api_v1_clients_get"];
        put?: never;
        /** Create Client */
        post: operations["create_client_api_v1_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client */
        get: operations["get_client_api_v1_clients__client_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Client
         * @description Deactivate rather than erase.
         *
         *     Visits reference this row, and a signed note is a legal record. Removing the row
         *     would orphan documentation the user may be required to produce later.
         */
        delete: operations["delete_client_api_v1_clients__client_id__delete"];
        options?: never;
        head?: never;
        /** Update Client */
        patch: operations["update_client_api_v1_clients__client_id__patch"];
        trace?: never;
    };
    "/api/v1/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Visit
         * @description Open a visit.
         *
         *     A replayed idempotency key answers 200 with the existing visit rather than 201,
         *     so a client can tell whether its retry created anything.
         */
        post: operations["create_visit_api_v1_visits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visits/{visit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Visit */
        get: operations["get_visit_api_v1_visits__visit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visits/{visit_id}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin Upload
         * @description Negotiate an upload.
         *
         *     Returns a single presigned PUT for a small file, or a multipart upload with one
         *     URL per part for anything sizeable. Bytes go straight to the bucket; they never
         *     pass through this API.
         */
        post: operations["begin_upload_api_v1_visits__visit_id__upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visits/{visit_id}/upload/parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reissue Parts
         * @description Fresh URLs for parts that have not finished, so an interrupted upload resumes.
         */
        post: operations["reissue_parts_api_v1_visits__visit_id__upload_parts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visits/{visit_id}/upload/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Upload
         * @description Finish the upload and hand the visit to the worker.
         *
         *     Enqueueing happens here rather than at visit creation: until the object exists
         *     in the bucket there is nothing for the pipeline to fetch, and a worker sent
         *     after audio that has not arrived yet would fail every time.
         */
        post: operations["complete_upload_api_v1_visits__visit_id__upload_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visits/{visit_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Visit Status
         * @description What the capture screen polls while the note is being written.
         *
         *     Reports the pipeline stage alongside the visit status, because "processing" for
         *     twenty minutes and "stuck" look identical to a client that is only told the
         *     latter.
         */
        get: operations["visit_status_api_v1_visits__visit_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Note */
        get: operations["read_note_api_v1_notes__note_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Jobs newest first, optionally filtered by status.
         *
         *     The filter is the reason the console exists: an operator opens it to find what
         *     broke, and paging through successful jobs to reach the failures would make it
         *     useless at exactly the moment it is needed.
         */
        get: operations["list_jobs_api_v1_ops_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/jobs/{visit_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Job
         * @description Put a job back on the queue.
         *
         *     The attempt counter is not reset. An operator retry is a further attempt at the
         *     same work, and clearing the history would hide a visit that has now failed six
         *     times behind a job that looks fresh.
         */
        post: operations["retry_job_api_v1_ops_jobs__visit_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Capabilities
         * @description What this account may do, decided from its jurisdiction.
         *
         *     Published so the client can stop offering what the server will refuse. It is not
         *     the enforcement: every rule here is checked again, against the user's current row,
         *     on the request that depends on it. That matters because these limits change
         *     without a new session -- a jurisdiction switch takes effect on the next request,
         *     and a capability minted into a bearer token would outlive the switch that revoked
         *     it.
         */
        Capabilities: {
            /** Allowed Capture Modes */
            allowed_capture_modes: components["schemas"]["CaptureMode"][];
            capture_restriction: components["schemas"]["CaptureRestrictionRead"] | null;
            /** Available Formats */
            available_formats: components["schemas"]["NoteFormat"][];
        };
        /**
         * CaptureMode
         * @description How the audio was obtained.
         *
         *     The distinction is legal, not technical: live_audio records a third party and
         *     requires their acknowledgment, spoken_recap is the user dictating afterwards and
         *     records nobody else.
         * @enum {string}
         */
        CaptureMode: "live_audio" | "spoken_recap";
        /**
         * CaptureRestrictionRead
         * @description A capture mode this account may not use, and the statute that says so.
         */
        CaptureRestrictionRead: {
            /** Code */
            code: string;
            mode: components["schemas"]["CaptureMode"];
            /** Message */
            message: string;
        };
        /** ClientCreate */
        ClientCreate: {
            /** Label */
            label: string;
        };
        /** ClientRead */
        ClientRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Is Active */
            is_active: boolean;
        };
        /** ClientUpdate */
        ClientUpdate: {
            /** Label */
            label?: string | null;
        };
        /** CompletedPartIn */
        CompletedPartIn: {
            /** Part Number */
            part_number: number;
            /** Etag */
            etag: string;
        };
        /** Credentials */
        Credentials: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** DependencyHealth */
        DependencyHealth: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
            /** Latency Ms */
            latency_ms?: number | null;
            /** Error */
            error?: string | null;
        };
        /**
         * FlagSeverity
         * @enum {string}
         */
        FlagSeverity: "info" | "warning" | "critical";
        /** GoogleSignInRequest */
        GoogleSignInRequest: {
            /** Id Token */
            id_token: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Environment */
            environment: string;
            /** Version */
            version: string;
            /** Dependencies */
            dependencies?: {
                [key: string]: components["schemas"]["DependencyHealth"];
            };
        };
        /**
         * JobStage
         * @description How far the pipeline got.
         *
         *     Recorded because "it failed" is not actionable and "it failed at transcription"
         *     is: the two failures have different causes, different costs, and different fixes.
         * @enum {string}
         */
        JobStage: "queued" | "download" | "normalize" | "transcribe" | "generate" | "persist" | "complete";
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed";
        /**
         * Jurisdiction
         * @description Which regulatory regime a user, visit, and note template belong to.
         *
         *     Stored as CHAR(2) with a check constraint rather than a Postgres ENUM, because
         *     the set grows and ALTER TYPE cannot run inside a transaction block.
         * @enum {string}
         */
        Jurisdiction: "US" | "PH";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** NoteFlagRead */
        NoteFlagRead: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            severity: components["schemas"]["FlagSeverity"];
        };
        /**
         * NoteFormat
         * @enum {string}
         */
        NoteFormat: "shift_note" | "soapie" | "fdar";
        /** NoteRead */
        NoteRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Visit Id
             * Format: uuid
             */
            visit_id: string;
            format: components["schemas"]["NoteFormat"];
            /** Version */
            version: number;
            /** Edited */
            edited: boolean;
            review_status: components["schemas"]["ReviewStatus"];
            /** Signed At */
            signed_at: string | null;
            /** Visit Details */
            visit_details: {
                [key: string]: unknown;
            };
            /** Sections */
            sections: {
                [key: string]: string | {
                    [key: string]: string | null;
                }[] | null;
            };
            /** Flags */
            flags: components["schemas"]["NoteFlagRead"][];
            template: components["schemas"]["TemplateRead"];
        };
        /**
         * OnboardingRequest
         * @description Partial profile update.
         *
         *     `extra="forbid"` is a security control, not tidiness: without it a client could
         *     post is_staff and, if the handler ever grew a loop over the payload, escalate
         *     privilege. Rejecting unknown fields makes that class of bug impossible to write.
         */
        OnboardingRequest: {
            /** Full Name */
            full_name?: string | null;
            role_title?: components["schemas"]["RoleTitle"] | null;
            default_note_format?: components["schemas"]["NoteFormat"] | null;
            /** Timezone */
            timezone?: string | null;
            jurisdiction?: components["schemas"]["Jurisdiction"] | null;
        };
        /** OpsJob */
        OpsJob: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Visit Id
             * Format: uuid
             */
            visit_id: string;
            stage: components["schemas"]["JobStage"];
            status: components["schemas"]["JobStatus"];
            /** Attempts */
            attempts: number;
            /** Error Message */
            error_message: string | null;
            /** Audio Minutes */
            audio_minutes: string | null;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Cost Usd */
            cost_usd: string | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Trace Id */
            trace_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** OpsJobPage */
        OpsJobPage: {
            /** Items */
            items: components["schemas"]["OpsJob"][];
            /** Total */
            total: number;
        };
        /** PartUrl */
        PartUrl: {
            /** Part Number */
            part_number: number;
            /** Url */
            url: string;
        };
        /** PartsRequest */
        PartsRequest: {
            /** Part Numbers */
            part_numbers: number[];
        };
        /** PartsResponse */
        PartsResponse: {
            /** Upload Id */
            upload_id: string;
            /** Parts */
            parts: components["schemas"]["PartUrl"][];
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * ReviewStatus
         * @description Where a note sits in an agency's review workflow.
         *
         *     Separate from the visit's status: a note can be signed by its author and still
         *     be waiting on a supervisor, and those are different questions.
         * @enum {string}
         */
        ReviewStatus: "unreviewed" | "needs_correction" | "accepted";
        /**
         * RoleTitle
         * @description What the user does, which sets their default note format at onboarding.
         * @enum {string}
         */
        RoleTitle: "caregiver" | "hha" | "cna" | "lpn" | "rn" | "other";
        /** SectionSpecRead */
        SectionSpecRead: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Order */
            order: number;
            /** Description */
            description: string;
            /** Repeating */
            repeating: boolean;
            /** Fields */
            fields: components["schemas"]["SectionSpecRead"][];
        };
        /** TemplateRead */
        TemplateRead: {
            jurisdiction: components["schemas"]["Jurisdiction"];
            format: components["schemas"]["NoteFormat"];
            /** Version */
            version: number;
            /** Name */
            name: string;
            /** Sections */
            sections: components["schemas"]["SectionSpecRead"][];
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** UploadBegin */
        UploadBegin: {
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** UploadComplete */
        UploadComplete: {
            /** Parts */
            parts?: components["schemas"]["CompletedPartIn"][];
        };
        /** UploadTicket */
        UploadTicket: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "single" | "multipart";
            /** Url */
            url?: string | null;
            /** Upload Id */
            upload_id?: string | null;
            /** Part Size Bytes */
            part_size_bytes?: number | null;
            /** Parts */
            parts: components["schemas"]["PartUrl"][];
        };
        /** UserProfile */
        UserProfile: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string | null;
            role_title: components["schemas"]["RoleTitle"] | null;
            default_note_format: components["schemas"]["NoteFormat"] | null;
            /** Timezone */
            timezone: string;
            jurisdiction: components["schemas"]["Jurisdiction"];
            /** Is Staff */
            is_staff: boolean;
            capabilities: components["schemas"]["Capabilities"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VisitCreate */
        VisitCreate: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            capture_mode: components["schemas"]["CaptureMode"];
            /** Idempotency Key */
            idempotency_key: string;
            note_format?: components["schemas"]["NoteFormat"] | null;
            /**
             * Consent Acknowledged
             * @default false
             */
            consent_acknowledged: boolean;
        };
        /**
         * VisitProcessingStatus
         * @description What the capture screen polls while a note is being written.
         *
         *     `stage` and `attempts` are included because "processing" for twenty minutes is
         *     indistinguishable from "stuck", and a client that cannot tell the difference
         *     either worries the user or hides a real failure.
         */
        VisitProcessingStatus: {
            /**
             * Visit Id
             * Format: uuid
             */
            visit_id: string;
            status: components["schemas"]["VisitStatus"];
            stage?: components["schemas"]["JobStage"] | null;
            job_status?: components["schemas"]["JobStatus"] | null;
            /**
             * Attempts
             * @default 0
             */
            attempts: number;
            /** Error */
            error?: string | null;
            /** Note Id */
            note_id?: string | null;
        };
        /** VisitRead */
        VisitRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            jurisdiction: components["schemas"]["Jurisdiction"];
            note_format: components["schemas"]["NoteFormat"];
            capture_mode: components["schemas"]["CaptureMode"];
            status: components["schemas"]["VisitStatus"];
            /** Timezone */
            timezone: string;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Audio Key */
            audio_key: string | null;
        };
        /**
         * VisitStatus
         * @enum {string}
         */
        VisitStatus: "recording" | "uploaded" | "processing" | "ready" | "signed" | "failed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description One or more dependencies are unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    update_me_api_v1_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_sign_in_api_v1_auth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleSignInRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_api_v1_clients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"][];
                };
            };
        };
    };
    create_client_api_v1_clients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_api_v1_clients__client_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_client_api_v1_clients__client_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_client_api_v1_clients__client_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_visit_api_v1_visits_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisitCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_visit_api_v1_visits__visit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    begin_upload_api_v1_visits__visit_id__upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadBegin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadTicket"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reissue_parts_api_v1_visits__visit_id__upload_parts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_upload_api_v1_visits__visit_id__upload_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadComplete"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    visit_status_api_v1_visits__visit_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitProcessingStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_note_api_v1_notes__note_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_ops_jobs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["JobStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsJobPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_v1_ops_jobs__visit_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
