"""LLM provider seam.

The protocol exists so that the pipeline, the evals, and the tracing layer never see
an SDK type. A test that can drive generation with no API key and no network is the
proof that the seam actually holds.
"""

import pytest

from app.llm.providers import (
    FakeLLMProvider,
    LLMOutputError,
    get_llm_provider,
)

SCHEMA = {
    "type": "object",
    "properties": {"sections": {"type": "object"}, "flags": {"type": "array"}},
    "required": ["sections", "flags"],
}


async def test_fake_provider_returns_the_scripted_payload() -> None:
    payload = {"sections": {"handover": "Bring more gauze."}, "flags": []}
    provider = FakeLLMProvider(responses=[payload])

    result = await provider.complete_json(
        system="you are a scribe", user="transcript", schema=SCHEMA, model_id="fake-1"
    )

    assert result.data == payload


async def test_fake_provider_reports_usage_and_the_model_it_was_asked_for() -> None:
    """Cost accounting reads these; a provider that omits them makes margin invisible."""
    provider = FakeLLMProvider(responses=[{"sections": {}, "flags": []}])

    result = await provider.complete_json(
        system="s", user="u", schema=SCHEMA, model_id="claude-test-1"
    )

    assert result.usage.model_id == "claude-test-1"
    assert result.usage.input_tokens > 0
    assert result.usage.output_tokens > 0
    assert result.usage.latency_ms >= 0


async def test_fake_provider_walks_scripted_responses_in_order() -> None:
    """The repair retry needs a first response that fails validation and a second that does not."""
    provider = FakeLLMProvider(
        responses=[{"sections": {}, "flags": "not-a-list"}, {"sections": {}, "flags": []}]
    )

    first = await provider.complete_json(system="s", user="u", schema=SCHEMA, model_id="m")
    second = await provider.complete_json(system="s", user="u", schema=SCHEMA, model_id="m")

    assert first.data["flags"] == "not-a-list"
    assert second.data["flags"] == []


async def test_fake_provider_records_the_prompts_it_was_given() -> None:
    """Prompt-construction tests assert against what the provider actually received."""
    provider = FakeLLMProvider(responses=[{"sections": {}, "flags": []}])

    await provider.complete_json(
        system="system rules", user="speaker_0: hello", schema=SCHEMA, model_id="m"
    )

    assert provider.calls[0].system == "system rules"
    assert provider.calls[0].user == "speaker_0: hello"


async def test_fake_provider_can_be_scripted_to_fail() -> None:
    """Retry and failure paths need a provider that raises the protocol's own error."""
    provider = FakeLLMProvider(responses=[LLMOutputError("model returned prose, not JSON")])

    with pytest.raises(LLMOutputError):
        await provider.complete_json(system="s", user="u", schema=SCHEMA, model_id="m")


def test_provider_selection_falls_back_to_the_fake_without_credentials() -> None:
    get_llm_provider.cache_clear()

    assert isinstance(get_llm_provider(), FakeLLMProvider)

    get_llm_provider.cache_clear()


def test_provider_selection_refuses_to_start_production_without_credentials(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A production note generated by a fixture provider would be a fabricated record."""
    from app.core.config import get_settings

    monkeypatch.setattr(get_settings(), "environment", "production")
    get_llm_provider.cache_clear()

    with pytest.raises(RuntimeError, match="LLM provider is not configured"):
        get_llm_provider()

    get_llm_provider.cache_clear()


def test_provider_selection_uses_anthropic_when_a_key_is_present(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    from app.core.config import get_settings
    from app.llm.providers.anthropic import AnthropicProvider

    monkeypatch.setattr(get_settings(), "anthropic_api_key", "sk-ant-test")
    get_llm_provider.cache_clear()

    assert isinstance(get_llm_provider(), AnthropicProvider)

    get_llm_provider.cache_clear()


async def test_an_unscripted_fake_satisfies_the_schema_it_is_given() -> None:
    """Local development has no API key, so this fake is what runs the pipeline.

    A fixed payload could not satisfy both note formats, so an unscripted fake
    derives its answer from the schema it was handed. Without this, `docker compose
    up` produces a product where every recording fails at generation.
    """
    schema = {
        "type": "object",
        "properties": {
            "visit_details": {
                "type": "object",
                "properties": {"client_label": {}, "visit_date": {}},
            },
            "sections": {
                "type": "object",
                "properties": {"observations": {}, "handover": {}},
            },
            "flags": {"type": "array"},
        },
    }

    result = await FakeLLMProvider().complete_json(
        system="s", user="u", schema=schema, model_id="m"
    )

    assert set(result.data["sections"]) == {"observations", "handover"}
    assert set(result.data["visit_details"]) == {"client_label", "visit_date"}
    assert result.data["flags"] == []


async def test_an_unscripted_fake_emits_entries_for_a_repeating_section() -> None:
    """FDAR's focus_entries is an array of objects, not a string like every other
    section. Against the real seeded FDAR schema, a fixed string there fails
    validate_output, and the fake is sticky -- the repair attempt returns the same
    payload, so the run ends in a non-retryable PipelineError on the one format this
    phase exists to add.
    """
    from app.llm.providers.fake import PLACEHOLDER

    schema = {
        "type": "object",
        "properties": {
            "visit_details": {"type": "object", "properties": {"client_label": {}}},
            "sections": {
                "type": "object",
                "properties": {
                    "shift_details": {"type": ["string", "null"]},
                    "focus_entries": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "focus": {},
                                "data": {},
                                "action": {},
                                "response": {},
                            },
                        },
                    },
                },
            },
            "flags": {"type": "array"},
        },
    }

    result = await FakeLLMProvider().complete_json(
        system="s", user="u", schema=schema, model_id="m"
    )

    entries = result.data["sections"]["focus_entries"]
    assert isinstance(entries, list)
    # Two entries, not one: a single entry would not exercise the multi-entry path a
    # repeating section exists for.
    assert len(entries) == 2
    for entry in entries:
        assert set(entry) == {"focus", "data", "action", "response"}

    # A non-repeating section in the same schema is unaffected by the change.
    assert result.data["sections"]["shift_details"] == PLACEHOLDER


async def test_an_unscripted_fake_makes_it_obvious_the_note_is_not_real() -> None:
    """A placeholder that reads like a real note is a trap for whoever sees it next."""
    schema = {
        "type": "object",
        "properties": {
            "visit_details": {"type": "object", "properties": {"client_label": {}}},
            "sections": {"type": "object", "properties": {"observations": {}}},
            "flags": {"type": "array"},
        },
    }

    result = await FakeLLMProvider().complete_json(
        system="s", user="u", schema=schema, model_id="m"
    )

    assert "fake" in str(result.data["sections"]["observations"]).lower()
