"""Per-note cost accounting.

Every job records what the note cost to produce: audio minutes, input and output
tokens, and the computed dollar figure. Without it the operator console can show
throughput but not margin, and margin is the number that decides whether the product
works at the price it is sold for.

All arithmetic is Decimal. These are fractions of a cent multiplied by millions of
tokens; binary floating point turns that into a figure with a trailing 0.000000001
that makes the whole column look unreliable.
"""

import logging
from decimal import Decimal

from pydantic import BaseModel

logger = logging.getLogger(__name__)

_TOKENS_PER_MILLION = Decimal(1_000_000)


class ModelPrice(BaseModel):
    """Published rates for one model, in USD per million tokens."""

    input_usd_per_mtok: Decimal
    output_usd_per_mtok: Decimal


def compute_cost(
    *,
    model_id: str,
    input_tokens: int,
    output_tokens: int,
    audio_minutes: Decimal,
    prices: dict[str, ModelPrice],
    transcription_usd_per_minute: Decimal,
) -> Decimal | None:
    """What this note cost, or None if the model has no configured price.

    None rather than zero, deliberately. An unpriced model is a configuration gap,
    and recording it as free would quietly overstate margin on exactly the notes
    generated by a model nobody has costed yet -- which is to say, the new one.
    """
    price = prices.get(model_id)
    if price is None:
        logger.warning(
            "no price configured for model; cost will not be recorded",
            extra={"model_id": model_id},
        )
        return None

    generation = (
        Decimal(input_tokens) * price.input_usd_per_mtok
        + Decimal(output_tokens) * price.output_usd_per_mtok
    ) / _TOKENS_PER_MILLION

    return generation + audio_minutes * transcription_usd_per_minute
